apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/redis-docker/
  - ../../base/postgres-docker/
  - ../../base/django/

patches:
  - path: patches/django-migration.yaml
    target:
      version: v1
      kind: Job
      name: django-migrations-job