apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/redis-docker/
  - ../../base/django/

patchesJson6902:
    - target:
      version: v1
      kind: ConfigMap
      name: django-configmap
    path: patches/configmap.yaml
  - target:
      version: v1
      kind: Job
      name: django-migrations-job
    path: patches/migration-job.yaml
